<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.8" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\safety_regression\**\*Tests.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BloodBankLIS.Infrastructure\BloodBankLIS.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\BloodBankLIS.Application\BloodBankLIS.Application.csproj" />
    <ProjectReference Include="..\..\src\BloodBankLIS.Domain\BloodBankLIS.Domain.csproj" />
    <ProjectReference Include="..\..\src\BloodBankLIS.HL7\BloodBankLIS.HL7.csproj" />
    <ProjectReference Include="..\..\src\BloodBankLIS.Printing\BloodBankLIS.Printing.csproj" />
    <ProjectReference Include="..\..\src\BloodBankLIS.Security\BloodBankLIS.Security.csproj" />
  </ItemGroup>

</Project>